version: '3.9'

services:
    napa-api:
        build: ./api
        volumes:
            - ./api:/app
        container_name: napa-api
        command: bash -c "uvicorn main:app --host 0.0.0.0 --port 160 --reload"
        ports:
            - 160:160
        networks:
            - napa-api

    napa-mongodb:
        container_name: napa-mongodb
        image: mongo:5.0.3
        command: mongod --port 161
        restart: always
        environment:
            - MONGO_INITDB_DATABASE=napa
            - MONGODB_DATA_DIR=/data/db
        volumes:
            - ./data:/data/db
        networks:
            - napa-api


volumes:
    data:

networks:
    napa-api:
        driver: bridge
